---
- name: Initial setup VM
  hosts: proxmox
  vars:
    api_host: 'host-ip'
    api_user: root@pam
    api_password: 'passwort'
    node: node-pve
    clone_vm: debian12-cloudinit
    name: vm-name
    vmid: 2005
    ipaddress: 192.168.1.2/24
    gwaddress: '192.168.1.1'
    cores: 2
    memory: 4096
    sockets: 1

  tasks:
    - name: Clone VMs
      proxmox_kvm:
        node: "{{ node }}"
        name: "{{ name }}"
        newid: "{{ vmid }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        api_host: "{{ api_host }}"
        clone: "{{ clone_vm }}"
        full: yes
        timeout: 300

    - name: Set IP addresses
      command: "qm set {{ vmid }}  --ipconfig0 ip={{ ipaddress }},gw={{ gwaddress }}"

    - name: Update VMs
      proxmox_kvm:
        api_host:     "{{ api_host }}"
        api_user:     "{{ api_user }}"
        api_password: "{{ api_password }}"
        cores:        "{{ cores }}"
        sockets:      "{{ sockets }}"
        memory:       "{{ memory }}"
        update:       yes
        vmid:         "{{ vmid }}"
        node:         "{{ node }}"
        name:         "{{ name }}"
        timeout: 300

    - name: Start VMs
      proxmox_kvm:
        api_host:     "{{ api_host }}"
        api_password: "{{ api_password }}"
        api_user:     "{{ api_user }}"
        vmid:         "{{ vmid }}"
        node:         "{{ node }}"
        state:        started
        timeout: 300